-- Run this in Supabase SQL Editor after creating the three Auth users.
-- Replace the email values with the real emails you create in Authentication > Users.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  ip text,
  user_agent text,
  device text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.login_events enable row level security;
alter table public.knowledge_items enable row level security;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('profiles', 'login_events', 'knowledge_items')
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end $$;

drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "knowledge read authenticated" on public.knowledge_items;
create policy "knowledge read authenticated"
on public.knowledge_items for select
to authenticated
using (true);

drop policy if exists "knowledge edit editor admin" on public.knowledge_items;
create policy "knowledge edit editor admin"
on public.knowledge_items for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('editor', 'admin')
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('editor', 'admin')
  )
);

drop policy if exists "login events admin read" on public.login_events;
create policy "login events admin read"
on public.login_events for select
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);

-- Insert roles after creating Auth users. Edit these emails first.
-- insert into public.profiles (id, email, role)
-- select id, email, 'admin' from auth.users where email = 'admin@example.com'
-- on conflict (id) do update set role = excluded.role, email = excluded.email;
--
-- insert into public.profiles (id, email, role)
-- select id, email, 'editor' from auth.users where email = 'editor@example.com'
-- on conflict (id) do update set role = excluded.role, email = excluded.email;
--
-- insert into public.profiles (id, email, role)
-- select id, email, 'viewer' from auth.users where email = 'student@example.com'
-- on conflict (id) do update set role = excluded.role, email = excluded.email;
